events {
    worker_connections 1024;
}

http {
    upstream backend_cluster {
        server web-n01:3000;
        server web-n02:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
